apiVersion: v1
kind: Service
metadata:
  name: healthcare-crm-gateway-service
  namespace: healthcare-crm-stage
spec:
  type: LoadBalancer
  selector:
    app: healthcare-crm-gateway-deployment
  ports:
  - port: 8005
