apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-crm-pharmacy-deployment
  namespace: healthcare-crm-stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare-crm-pharmacy-deployment
  template:
    metadata:
      labels:
        app: healthcare-crm-pharmacy-deployment
    spec:
      containers:
      - name: healthcare-crm-pharmacy-deployment
        image: aravindarivi1997/healthcare-crmbackend-pharmacy
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8001
